User.create(username: "billylitt", password: "password")
User.create(username: "GShorr", password: "password")
User.create(username: "TallRob42", password: "password")

Workout.create(user_id: 1, title: "Short run through Schenley", activity: "Run", date: Date.new(2015,10,15), distance: 5.32, duration: "00:35:00", notes: "Feeling good today!")
Workout.create(user_id: 1, title: "Quick thru Frick", activity: "Run", date: Date.new(2015,10,16), distance: 8, duration: "00:56:00", notes: "Saw Mac Miller!")
Workout.create(user_id: 1, title: "Long run downtown", activity: "Run", date: Date.new(2015,11,01), distance: 0, duration: "01:30:00", notes: "Man my legs are dead")
Workout.create(user_id: 2, title: "Alumni pre-race", activity: "Bike", date: Date.new(2015,10,15), distance: 12, duration: "01:35:00", notes: "Hammies are sore")
Workout.create(user_id: 2, title: "POST RACE BABYY", activity: "Run", date: Date.new(2015,10,16), distance: 7, duration: "00:35:30", notes: "Crushed it")
Workout.create(user_id: 3, title: "Durham forest", activity: "Run", date: Date.new(2015,10,18), distance: 12, duration: "00:35:00", notes: "Feeling good today!")
Workout.create(user_id: 3, title: "Double, ran in the evening", activity: "Run", date: Date.new(2015,10,18), distance: 4, duration: "00:20:00", notes: "Flying")
